### ISSUE TITLE
Multi trades

### ISSUE THREAD

**Issue by bdawg1989** [Sadlamulk/TransFireBot#55]
Hello!  Does your sysBOT offer multi trades?

**Comment by Sadlamulk** [comment]
yes

**Comment by bdawg1989** [comment]
Amazing. Can it be implemented for discord too?  Or not?

**Comment by Sadlamulk** [comment]
sorry I cant support discord or twitch But maybe you can check this one
https://github.com/easyworld/SysBot.NET/commit/bfaac0eb5e24e19916bda5cd913b7332797aace9
